### ISSUE TITLE
Episode status reverts to Recording from FInished after WorkflowCleanupScanner

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1596] opened 2020-05-22 22:30 UTC
Migrated from [MH-12081](https://opencast.jira.com/browse/MH-12081)

**Describe the bug**
Recordings in Finished state revert to Recording state after WorkflowCleanupScanner cleans up their backing jobs.

**To Reproduce**
1. Set enabled to true in https://bitbucket.org/opencast-community/matterhorn/src/445645a2d58be8bd25ec44ba7ab6f9342118aee2/etc/org.opencastproject.workflow.impl.WorkflowCleanupScanner.cfg?at=r%2F2.2.x&fileviewer=file-view-default
2. Wait for the job to run
3. Inspect the results in the admin interface. We had about 440 jobs with status finished, after the run, there were only about 320 showing as finished; the remaining finished ones show up as recording
 
**Environment Information**
 - Opencast 2.2 and newer

**Comment by Rillke** [comment] 2020-05-23 07:30
Working URL: https://github.com/opencast/opencast/blob/r/8.x/etc/org.opencastproject.workflow.impl.WorkflowCleanupScanner.cfg#L3

**Comment by lkiesow** [comment] 2020-11-12 11:12
Some additional findings:

- @Rillke pointed out that this might be caused by the changes in https://github.com/opencast/opencast/commit/89bf9ca32f4debe5b5b8e163ea131191245bb182
- The issue does not appear on non-scheduled events (tested against develop and 8.x)

**Comment by Rillke** [comment] 2020-11-12 16:47
> @Rillke pointed out that this might be caused by the changes in 89bf9ca

To be clear, 89bf9ca prevents a customer from re-processing (i.e. starting actions on) archived material because it is in recording state and thus an action was required from my part in order to allow the customer to continue re-publishing archived material. 89bf9ca is unrelated to the issue that the state of some events reverts to "recording" after workflow information on it has been deleted by the WorkflowCleanupScanner.

**Comment by mheyen** [comment] 2020-11-16 14:22
I was not able to reproduce this so far. 

However, the status of a scheduled event changes from `Finished` to `Ingesting` when I delete the Workflow of the event. 
This happened in develop and r/8.x .
I was not able to start a new workflow with `Start Task`.

**Comment by Rillke** [comment] 2020-11-16 20:28
> I was not able to reproduce this so far.

Do you need access to our Opencast instance? If so, please email us.

**Comment by Rillke** [comment] 2021-01-12 23:51
@mheyen Would you like to get access to our Opencast instance?

**Comment by mheyen** [comment] 2021-01-18 09:45
sorry for the late reply. I am afraid I am currently not going to look into this, and am probably not the right person to tackle this anyway :)

**Comment by mliradelc** [comment] 2021-06-15 14:39
I will close this issue because #2676 solves it

**Closed as completed by mliradelc** 2021-06-15 14:39 UTC
Labels: bug
