### ISSUE TITLE
Adding LTI deeplink as a tool to the LTI module

### ISSUE THREAD

**Issue by kristofkeppens** [opencast/opencast#2164] opened 2020-12-17 13:14 UTC
The LTI module now does not have an easy way to integrate content into the LMS. Via the LTI deeplink mechanism an end user can easily add videos to their LMS course.

This issue aims to fix this by adding a new tool to the LTI module, deeplink.

**Comment by lkiesow** [comment] 2020-12-22 18:37
Closing this since it is basically a duplicate of  #2165

**Closed as completed by lkiesow** 2020-12-22 18:37 UTC
