### ISSUE TITLE
Clean Install: Firefox related tests fail in admin-ui-frontend (macOS)

### ISSUE THREAD

**Issue by owi92** [opencast/opencast#3894] opened 2022-06-21 17:48 UTC
**Issue**
When installing Opencast on macOS via $ `mvn clean install -Pdev -DtrimStackTrace=false` a total of 41 Firefox related tests fail in the admin-ui-frontend bundle.
33 of these tests seem to be related to `adminNg.services.language`
In each case there is an error reading:
```
[INFO] 	Error: Unexpected request: GET public/org/opencastproject/adminui/languages/lang-de_DE.json 
[INFO] 	No more request expected in /Users/dude/Documents/dev/work/opencast/modules/admin-ui-frontend/bower_components/angular-mocks/angular-mocks.js (line 1569)
```
See the "grepped" log file below for a description of each failed test.

**To Reproduce**
1. clone opencast repository
2. $ `mvn clean install -Pdev`
3. see output - _note_: apparently this only occurs on macOS

**Workaround**
open `opencast/modules/admin-ui-frontend/test/karma.conf.js` and edit the following line (should be around line 69):
`const allowed = new Set(['ChromeHeadless', 'FirefoxHeadless'])`
to
`const allowed = new Set(['ChromeHeadless'])`

**Environment Information**
 - OS: [macOS 12.4 with M1 - this also happens on an old intel machine with macOS 10.15]
 - Browser [Firefox 101.0.1]
 - Opencast version [develop branch - opencast 13.x?]
 
**Log**
[install-errors.log](https://github.com/opencast/opencast/files/8950902/install-errors.log)

**Comment by gregorydlogan** [comment] 2022-06-21 18:56
Just to be sure: you do have Firefox installed, right?

**Comment by owi92** [comment] 2022-06-21 21:40
Yes, it is my default browser.

**Comment by gregorydlogan** [comment] 2022-06-24 21:54
@mliradelc you've got an M series mac right?  I'm assuming you can't reproduce this?

**Comment by mliradelc** [comment] 2022-06-28 13:58
Thanks, @gregorydlogan, for ping me, I will try on my M1

On my intel based mac, I don't have issues

**Comment by mliradelc** [comment] 2022-07-01 14:22
I just tried on my M1 pro, indeed, the build fails with Firefox.

I can confirm this bug, now, there are two workarounds:
- Uninstall Firefox
- Disable Firefox in tests when compiling under a M1 mac.

Nevertheless, we need a proper fix for this bug.  We removed safari tests because the plugin was very old, but with Firefox we can't have that luxury to not have it.

**Comment by snoesberger** [comment] 2023-12-05 07:25
I do have the same problem on my Mac (M1, Sonoma 14.1.2, Firefox 119.0.1). With the "disable Firefox" workaround, compiling works. But has anyone found a proper solution for this?

**Comment by karendolan** [comment] 2024-01-22 17:46
@snoesberger @mliradelc @gregorydlogan There is a FireFoxHeadless Karma patch but Karma says it's being deprecated and not accepting new patches...
The patch and concern that the patch might not be merged: https://github.com/karma-runner/karma-firefox-launcher/pull/330#issuecomment-1894137635
The reference stating that Karma is deprecated and not taking new patches: https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes

Until Opencast can migrate from Karma, or Karma allows that FireFoxHeadless patch, this suggestion to omit the FireFoxHeadless test is a good workaround for running tests on Mac OS X.

**Comment by gregorydlogan** [comment] 2024-01-22 19:47
CC @JulianKniephoff since he was running into this today.

Is there a way of getting Karma to do some logic wrt to which platforms it's testing based on their local arch?  It'd be nice if Mac devs didn't have to deal with this.

**Comment by JulianKniephoff** [comment] 2024-01-23 09:11
^ Yes there is ;D

**Closed as completed** 2024-01-30 09:01 UTC
