### ISSUE TITLE
Extended series metadata do not work with MariaDB

### ISSUE THREAD

**Issue by yokoul** [opencast/opencast#3914] opened 2022-06-29 07:28 UTC
**Describe the bug**
A clear and concise description of what you see:
*When i add an extend metadata catalog in serie i can display my metadata II in the interface, but soon as i set some data inside, it's crashing*

**To Reproduce**
1. Go to 'opencast and add an extended metadata catalog'
2. Add a test serie without extend metadata, everything is fine
3. Add a data in your metadata II
4. See error in your log (or in my log in this case)

```
2022-06-29T07:17:49,618 | ERROR | (ConfigurableSeriesDCCatalogUIAdapter:104) - Error while loading DublinCore catalog of series '54cc3d1d-4445-491b-9c7d-59410806f4cf': {}
org.opencastproject.series.api.SeriesException: org.opencastproject.series.impl.SeriesServiceDatabaseException: java.lang.ClassCastException: class org.mariadb.jdbc.MariaDbBlob cannot be cast to class [B (org.mariadb.jdbc.MariaDbBlob is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @40f2cab4; [B is in module java.base of loader 'bootstrap')
        at org.opencastproject.series.impl.SeriesServiceImpl.getSeriesElementData(SeriesServiceImpl.java:458) ~[?:?]
        at org.opencastproject.index.service.catalog.adapter.series.ConfigurableSeriesDCCatalogUIAdapter.loadDublinCoreCatalog(ConfigurableSeriesDCCatalogUIAdapter.java:87) [!/:?]
        at org.opencastproject.index.service.catalog.adapter.series.ConfigurableSeriesDCCatalogUIAdapter.getFields(ConfigurableSeriesDCCatalogUIAdapter.java:62) [!/:?]
        at org.opencastproject.adminui.endpoint.SeriesEndpoint.getSeriesMetadata(SeriesEndpoint.java:329) [!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [!/:3.4.6]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [!/:3.4.6]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [!/:3.4.6]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [!/:3.4.6]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [!/:3.4.6]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [!/:3.4.6]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [!/:3.4.6]
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [!/:3.4.6]
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [!/:3.4.6]
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [!/:3.4.6]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [!/:3.4.6]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [!/:3.4.6]
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [!/:3.4.6]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [!/:3.4.6]
        at org.opencastproject.kernel.rest.RestPublisher$RestServlet.handleRequest(RestPublisher.java:615) [!/:?]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) [!/:3.4.6]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [!/:3.1.0]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [!/:3.4.6]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) [!/:9.4.43.v20210629]
        at org.opencastproject.kernel.rest.JsonpFilter.doFilter(JsonpFilter.java:125) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.opencastproject.kernel.filter.proxy.TransparentProxyFilter.doFilter(TransparentProxyFilter.java:75) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.opencastproject.security.urlsigning.filter.UrlSigningFilter.doFilter(UrlSigningFilter.java:100) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.opencastproject.kernel.security.RemoteUserAndOrganizationFilter.doFilter(RemoteUserAndOrganizationFilter.java:260) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.opencastproject.kernel.rest.CurrentJobFilter.doFilter(CurrentJobFilter.java:101) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.opencastproject.kernel.security.AsyncTimeoutRedirectFilter.doFilter(AsyncTimeoutRedirectFilter.java:60) [!/:?]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:98) [!/:3.1.4.RELEASE]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) [!/:3.1.7.RELEASE]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:102) [!/:3.1.4.RELEASE]
        at org.springframework.security.web.authentication.www.DigestAuthenticationFilter.doFilter(DigestAuthenticationFilter.java:115) [!/:3.1.7.RELEASE]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:102) [!/:3.1.4.RELEASE]
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:82) [!/:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:91) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:183) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [!/:3.1.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [!/:3.1.7.RELEASE]
        at org.opencastproject.kernel.security.SecurityFilter.doFilter(SecurityFilter.java:138) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.opencastproject.kernel.security.OrganizationFilter.doFilter(OrganizationFilter.java:149) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.opencastproject.kernel.filter.https.HttpsFilter.doFilter(HttpsFilter.java:85) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.opencastproject.kernel.rest.CleanSessionsFilter.doFilter(CleanSessionsFilter.java:101) [!/:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) [!/:9.4.43.v20210629]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [!/:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) [!/:9.4.43.v20210629]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:298) [!/:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [!/:9.4.43.v20210629]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:82) [!/:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [!/:9.4.43.v20210629]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [!/:9.4.43.v20210629]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opencastproject.series.impl.SeriesServiceDatabaseException: java.lang.ClassCastException: class org.mariadb.jdbc.MariaDbBlob cannot be cast to class [B (org.mariadb.jdbc.MariaDbBlob is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @40f2cab4; [B is in module java.base of loader 'bootstrap')
        at org.opencastproject.series.impl.persistence.SeriesServiceDatabaseImpl.getSeriesElement(SeriesServiceDatabaseImpl.java:806) ~[?:?]
        at org.opencastproject.series.impl.SeriesServiceImpl.getSeriesElementData(SeriesServiceImpl.java:456) ~[?:?]
        ... 121 more
Caused by: java.lang.ClassCastException: class org.mariadb.jdbc.MariaDbBlob cannot be cast to class [B (org.mariadb.jdbc.MariaDbBlob is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @40f2cab4; [B is in module java.base of loader 'bootstrap')
        at org.opencastproject.series.impl.persistence.SeriesServiceDatabaseImpl.getSeriesElement(SeriesServiceDatabaseImpl.java:800) ~[?:?]
        at org.opencastproject.series.impl.SeriesServiceImpl.getSeriesElementData(SeriesServiceImpl.java:456) ~[?:?]
        ... 121 more
```

**Environment Information**
 - Server OS: [Ubuntu 22.04 LTS (GNU/Linux 5.15.0-1014-aws x86_64)]
 - Browser [all]
 - Opencast version with minor release [Opencast 12.0.0 - 085d2c6 - built on 2022-06-28]

**Comment by lkiesow** [comment] 2022-06-29 22:24
Can you paste your `CatalogUIAdapterFactory…cfg` for the extended series metadata catalog?

**Comment by yokoul** [comment] 2022-06-30 05:40
> Can you paste your `CatalogUIAdapterFactory…cfg` for the extended series metadata catalog?

```
type=series
organization=mh_default_org
title=test Series Metadata
flavor=test/series
common-metadata=false

# Name of the XML root element of the serialized catalog
xml.rootElement.name=test
# Namespace binding for the XML root element
xml.rootElement.namespace.URI=http://www.opencastproject.org/xsd/1.0/dublincore/

# XML namespace bindings
xml.namespaceBinding.root.URI=http://www.opencastproject.org/xsd/1.0/dublincore/
xml.namespaceBinding.root.prefix=
xml.namespaceBinding.dc.URI=http://purl.org/dc/elements/1.1/
xml.namespaceBinding.dc.prefix=test
xml.namespaceBinding.dcterms.URI=http://purl.org/dc/terms/
xml.namespaceBinding.dcterms.prefix=testterms

# CRM Event ID
property.testcrmeventid.inputID=testCRMEventID
property.testcrmeventid.label=CRM Event ID
property.testcrmeventid.type=text
property.testcrmeventid.readOnly=false
property.testcrmeventid.required=false
property.testcrmeventid.order=0
```
I played with somes options as the original one worked on r/11.x but didn't in r/12.0. I can make the event version work successfuly - without change from 11.x but nothing work for series.

**Comment by lkiesow** [comment] 2022-06-30 21:54
I've tried this with a fresh 12.x, and I cannot reproduce your issue at all. I've tried…

- creating a new series with extended metadata
- modifying the extended metadata later on
- manually creating a series without extended metadata, adding them later via admin ui

Everything worked just fine.
I've attached the configuration file I used, but it's basically just your configuration. I did not modify anything else in Opencast. It's just a bare allinone installation.

[org.opencastproject.ui.metadata.CatalogUIAdapterFactory-series-test.cfg.gz](https://github.com/opencast/opencast/files/9023623/org.opencastproject.ui.metadata.CatalogUIAdapterFactory-series-test.cfg.gz)

**Comment by yokoul** [comment] 2022-07-01 06:54
I can reproduce this on two different cluster who are both 12.0. 3 nodes (admin/presentation/worker) on public and RDS/EFS on private subnet. I don't have other related errors. Both are based on Ubuntu. I will test on a AllInOne instance to see if i can replicate it.

Maybe i'm doing the same configuration error who impact this process on both cluster and i don't see it yet. I will investigate more on my side. Thanks for your feedback Lars.

**Comment by lkiesow** [comment] 2022-07-03 20:57
I went from a 12.x to an Opencast 12.0.0 (085d2c6) cluster with PostgreSQL as a database and still everything works just fine.
The only differences now are that you are using MariaDB and potentially that you modified additional configuration.

**Comment by lkiesow** [comment] 2022-07-03 21:50
Good (?) news: It seems to be a problem related to MariaDB. I can reproduce this by switching from H2 or PostgreSQL to MariaDB.

It looks like the newer MariaDB JDBC driver has some issues. [CONJ-935](https://jira.mariadb.org/browse/CONJ-935) looks awfully similar, although that one got fixed in the version we have in 12.0. Our `develop` branch already has a newer version, and we should probably check if the error still appears there. If not, we can just update the driver in `12.x` as well.

Also, Liquibase tracked a series of seemingly related issues: https://github.com/liquibase/liquibase/issues/2431

**Comment by yokoul** [comment] 2022-07-03 21:58
Happy (or not..) you can reproduce it, was going creazy reading and reading again on my config to find an error. Thanks for investigating more Lars.

**Comment by lkiesow** [comment] 2022-07-04 09:16
And `develop` doesn't seem to have that problem. I can put out a patch later.
Could you test the patch in your deployment?

**Comment by lkiesow** [comment] 2022-07-04 09:56
Pull request is out. It would be great if you could test if that resolves the issue for you.

**Comment by yokoul** [comment] 2022-07-04 13:59
> Could you test the patch in your deployment?

I'm using package deployment, but i'm installing now a setup for testing it.

**Comment by lkiesow** [comment] 2022-07-04 15:02
You could just replace the `opencast-db` JAR files in `/usr/share/opencast/system/…` with the patched one. That will then automatically be overwritten with the next package update.

**Comment by yokoul** [comment] 2022-07-04 16:43
> You could just replace the `opencast-db` JAR files in `/usr/share/opencast/system/…` with the patched one. That will then automatically be overwritten with the next package update.

Thanks Lars, it was a better approach :-) I'm not dev at all... 
Ok, it's working perfectly with this change, thank you for this update.
![image](https://user-images.githubusercontent.com/630213/177193924-aed18027-b7f0-4083-859c-1cddb34c17e3.png)

**Closed as completed** 2022-07-04 16:47 UTC

**Comment by lkiesow** [comment] 2022-07-04 16:51
The patch will hopefully be reviewed in time for the 12.1 release next week.
