### ISSUE TITLE
Editor in admin interface broken

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1979] opened 2020-10-18 19:48 UTC
The admin interface's editor is completely broken in `r/9.x`. The player is shown but nothing else:

![Screenshot from 2020-10-18 21-45-59](https://user-images.githubusercontent.com/1008395/96378335-8e45d680-118b-11eb-8ba5-d91baa91bba5.png)

**Comment by mtneug** [comment] 2020-10-27 11:23
Duplicate of #1975

**Closed as completed by mtneug** 2020-10-27 11:23 UTC
Labels: bug, needs attention, javascript
