### ISSUE TITLE
LTI User Persistence creates too many users

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1690] opened 2020-07-15 20:57 UTC
**Describe the bug**
Per Ravishel Naicker on the users list, they have 30K+ students authenticating via LTI, with each one creating a new Opencast user in the database.  The majority of these users are viewer-only users, and should not exist in the database given their permissions.  Instead a regex, or other allow-list based system should be implemented to only persist users who need to be persisted (ie, Instructor roles).

**Comment by lkiesow** [comment] 2020-07-15 21:18
This was a deliberate choice I made and is not a bug. The feature is documented like this and intended to work like this.

https://github.com/opencast/opencast/blob/53263a8bfc788986f290c2019af62d0c93b99f6d/etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg#L51-L56

30k user is something Opencast can handle given an adequate system. But if it is a problem, they shouldn't use this feature. There are also other ways to archive the persistence of some users like the Moodle/Sakai user provider or even manually creating all relevant users.

@gregorydlogan, if you don't object, I tend to close this issue again.

**Comment by gregorydlogan** [comment] 2020-07-15 21:28
Just because Opencast *can*, does that mean it *should have to*?  Maybe bug here is the wrong tag, this is more of a feature request I guess.  If I were operating an Opencast install I would be surprised to see LTI users being created for every login without some way of pruning that back to only the ones necessary for their roles.  @DZenker at least seems to agree on list...

**Comment by lkiesow** [comment] 2020-07-15 21:57
With Opencast 8, you have to deliberately turn on this functionality. So, it can't be that surprising. But I've turned this into a feature request.

**Comment by gregorydlogan** [comment] 2020-08-04 21:04
Per discussion on list (`[OC Users] Opencast 8.3 slow admin ui and problem creating new series with admin ui`), this is showing up as a perf issue with large numbers of users causing slow response in the UI, or failure for responses to process (`java.lang.IllegalStateException: Form too large: 1676639 > 1500000`).  Disabling the relevant listproviders should remedy the lag, but this is obviously suboptimal since some of those users are no doubt presenters.

**Comment by lkiesow** [comment] 2020-11-06 11:39
To define what we need to do here:

Right now you can only turn persistence on or off:

https://github.com/opencast/opencast/blob/3a348ca4525efb0e2c183cd15f35b669909079df/etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg#L51-L56

Most of the time, it would suffice if we just persist people with certain __LTI roles__ (e.g. `Instructor`). We retrieve the role already before creating a new user reference and could easily decide based on this role if we want persistence or not:

https://github.com/opencast/opencast/blob/3a348ca4525efb0e2c183cd15f35b669909079df/modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java#L344

Thus, it would be nice to change the configuration to something like this:

```properties
# Determines if a user reference should be persisted in the database on LTI user logins.
# Persisting references gives the users the ability to create long running tasks like ingesting a video.
# The value can be a list of LTI roles identifying users to be persisted or the special value * causing all users to be persisted.
# The value is not case sensitive.
#
# Examples:
#  - Persist only instructors:
#    lti.create_jpa_user_reference = instructor
#  - Persist only instructors and administrators:
#    lti.create_jpa_user_reference.roles = instructor, administrator
#  - Persist all users:
#    lti.create_jpa_user_reference.roles = *
#  - No persistence:
#    lti.create_jpa_user_reference.roles =
#
# Default: instructor
#lti.create_jpa_user_reference.roles = instructor
```

**Comment by CGreweling** [comment] 2020-11-06 11:51
Defining users with specific roles to be presitent-users sounds good to me.
Looks good.

**Comment by Rillke** [comment] 2021-01-12 23:56
Backported this to r/8.x and it seems to work:

```
ajcay@ITZ-E-Team:~/git/opencast-docker$ docker-compose logs -f --tail 40 presentation |grep JpaUserReference
presentation_1        | 2021-01-13T00:27:31,178 | DEBUG | (LtiLaunchAuthenticationHandler:330) - No JpaUserReference will be created for LTI user lti:lms:rillke@wikipedia.de.
```

while instructors are still stored in the `oc_user_ref` table

Probably of note for anyone testing this: If the user is not persisted and one changes the roles submitted from the LTI client to include one that should be persisted and the user still exists in Opencast's memory, it won't persist the user.

**Closed as completed** 2022-01-03 09:19 UTC
Labels: performance, feature request
