### ISSUE TITLE
Opencast is not finding ActiveMQ which is running

### ISSUE THREAD

**Issue by Srinivasysr2003** [opencast/opencast#2184] opened 2021-01-01 04:32 UTC
**Describe the bug**
When I see system Notifications, I can see below 2 messages.
Active MQ Not Found
Service States Not Found

Opencast notification screenshot.
![image](https://user-images.githubusercontent.com/39143298/103433509-0d3d9d80-4c18-11eb-95df-31242c5d2473.png)

ActiveMQ Admin page screenshot which works fine.
![image](https://user-images.githubusercontent.com/39143298/103433520-3b22e200-4c18-11eb-9cce-0b5ac2413e6f.png)

**To Reproduce**
Followed the steps at: https://websiteforstudents.com/how-to-install-opencast-on-ubuntu-18-04-16-04/

**Environment Information**
 - OS: NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 - Browser: Mozilla 
 - Opencast version with minor release: 8.1

**Comment by gregorydlogan** [comment] 2021-01-01 15:24
A few things:

- Debian based systems have packages available. This is highly recommended versus manually installing, much less compiling from source! 
- Installation instructions *from our docs* are generally a better idea than finding something on an unrelated website online. 
- 8.1 is out of date, install 8.10, or better yet 9.1. This wouldn't affect the issue here though.
- You didn't configure the activemq settings in the main Opencast config file.

If you're still seeing issues after configuring activemq we would need to see the log file Opencast generates.

**Comment by lkiesow** [comment] 2021-01-01 19:07
Closing this since it's not confirmed on a supported version and I could not reproduce the issue.
Please re-open if there is a way to reproduce the issue.

**Closed as completed by lkiesow** 2021-01-01 19:07 UTC
