### ISSUE TITLE
Repeated "duplicate entry" warn messages in the log for session_id in table oc_user_session if user tracking is activated

### ISSUE THREAD

**Issue by DZenker** [opencast/opencast#2204] opened 2021-01-07 10:19 UTC
This issue has been reported a while ago in the Opencast user group, but no one had created an issue for that. If user tracking is activated, repeated duplicate entry warnings show up in the logs of the presentation node for primary key of session_id in table oc_user_session. This has been observed by several Opencast adopters.

**To Reproduce**
1. Activate user tracking in org.opencastproject.usertracking.impl.UserTrackingServiceImpl.cfg
2. Wait a while until users view events - BUT: this is not reproducible, as not all views provoke this!

**Environment Information**
 - OS: unknown
 - Browser: unknown
 - several Opencast versions: 7.x, 8.x

Here a sample from the log:
> ...
> 2020-04-24T10:01:06,506 | WARN  | (JavaLog:302) - org.eclipse.persistence.exceptions.DatabaseException: Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'node01u17m6me88ph61nzv7s0s1824l13593643' for key 'PRIMARY'
> Error Code: 1062 Call: INSERT INTO oc_user_session (session_id, user_agent, user_id, user_ip) VALUES (?, ?, ?, ?)
>         bind => [4 parameters bound]
> Query: InsertObjectQuery(org.opencastproject.usertracking.impl.UserSessionImpl@7d5babea)
>         at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:333) ~[232:org.eclipse.persistence.core:2.7.3.v20180807-4be1041]
> ...
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: org.opencastproject.usertracking.api.UserTrackingException: javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'node01u17m6me88ph61nzv7s0s1824l13593643' for key 'PRIMARY' Error Code: 1062
> Call: INSERT INTO oc_user_session (session_id, user_agent, user_id, user_ip) VALUES (?, ?, ?, ?) bind => [4 parameters bound] Query: InsertObjectQuery(org.opencastproject.usertracking.impl.UserSessionImpl@5c2b1514)
>         at org.opencastproject.usertracking.impl.UserTrackingServiceImpl.addUserTrackingEvent(UserTrackingServiceImpl.java:209)
>         at org.opencastproject.usertracking.endpoint.UserTrackingRestService.addFootprint(UserTrackingRestService.java:323)
>         ... 113 more
> Caused by: javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'node01u17m6me88ph61nzv7s0s1824l13593643' for key 'PRIMARY' Error Code: 1062
> Call: INSERT INTO oc_user_session (session_id, user_agent, user_id, user_ip) VALUES (?, ?, ?, ?)
>         bind => [4 parameters bound]
> Query: InsertObjectQuery(org.opencastproject.usertracking.impl.UserSessionImpl@5c2b1514)
>         at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:161)
>         at org.opencastproject.usertracking.impl.UserTrackingServiceImpl.addUserTrackingEvent(UserTrackingServiceImpl.java:203)
>         ... 114 more
> ...
> Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry  'node01d15mfjqba0mfge7ie8djmw6g13593928' for key 'PRIMARY' Error Code: 1062
> Call: INSERT INTO oc_user_session (session_id, user_agent, user_id, user_ip) VALUES (?, ?, ?, ?) bind => [4 parameters bound]
> Query: InsertObjectQuery(org.opencastproject.usertracking.impl.UserSessionImpl@29574cb5)
>         at org.opencastproject.usertracking.impl.UserTrackingServiceImpl.addUserTrackingEvent(UserTrackingServiceImpl.java:209)
>         at org.opencastproject.usertracking.endpoint.UserTrackingRestService.addFootprint(UserTrackingRestService.java:323)
>         ... 112 more
> Caused by: javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
> Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'node01d15mfjqba0mfge7ie8djmw6g13593928' for key 'PRIMARY' Error Code: 1062

After investigating this further, it's remarkable that ALL session ids that cause these errors start with "node01", BUT: in contrast, not every session id starting with "node01" causes these errors, some don't!

The db query results for the session ids that cause this errors are as follows:

> MariaDB [opencast7]> select * from oc_user_session where session_id like "node01u17m6me88ph61nzv7s0s1824l13593643" ;
> +-----------------------------------------+-----------+-------------------------------------------------------------------------------+-----------+
> | session_id                              | user_ip   | user_agent                                                                    | user_id   |
> +-----------------------------------------+-----------+-------------------------------------------------------------------------------+-----------+
> | node01u17m6me88ph61nzv7s0s1824l13593643 | -omitted- | Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0 | anonymous |
> +-----------------------------------------+-----------+-------------------------------------------------------------------------------+-----------+
> 1 row in set (0.00 sec)
> 
> MariaDB [opencast7]> select * from oc_user_session where session_id like "node01d15mfjqba0mfge7ie8djmw6g13593928" ;
> +----------------------------------------+-----------+--------------------------------------------------------------------------------+-----------+
> | session_id                             | user_ip   | user_agent                                                                     | user_id   |
> +----------------------------------------+-----------+--------------------------------------------------------------------------------+-----------+
> | node01d15mfjqba0mfge7ie8djmw6g13593928 | -omitted- | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0 | anonymous |
> +----------------------------------------+-----------+--------------------------------------------------------------------------------+-----------+
>

**Comment by lkiesow** [comment] 2021-01-07 16:52
Closing this as it is a duplicate of #1617

**Closed as completed by lkiesow** 2021-01-07 16:52 UTC
