### ISSUE TITLE
Admin interface access control display broken

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1969] opened 2020-10-15 21:24 UTC
If an access control list contains a role not provided in the admin interface's list provider for roles, the interface fails to display the role but displays an empty field instead: 

![Screenshot from 2020-10-15 23-19-06](https://user-images.githubusercontent.com/1008395/96187557-8690f280-0f3d-11eb-8323-47236fb79b27.png)

The problem appears on `develop` from 2020-10-15 and likely affects `r/9.x`

**Comment by lkiesow** [comment] 2020-12-03 15:36
Related to #1798

**Comment by wsmirnow** [comment] 2021-03-25 13:50
PR #2112 fixes the event details UI. But the issue is still exists in upload dialog. 
Reproduce steps:

0. Uncomment the custom roles pattern line in custom.properties https://github.com/opencast/opencast/blob/f99fc066c25e42f21d527fcd185936484e4e73a1/etc/custom.properties#L43 to enable the feature and (re)start Opencast
1. Create a series with uncommon role, like 12345_Instructor or 12345_Learner
2. Run Video Upload dialog and select the series created before
3. In the access control tab you will see empty roles, like in screenshot above

**Comment by wsmirnow** [comment] 2021-04-08 15:10
I've updated the instructions to reproduce the issue. Step 0. is added to clarify the dependant configuration.

**Comment by mtneug** [comment] 2021-04-26 08:36
Closing as PR is merged now

**Closed as completed by mtneug** 2021-04-26 08:36 UTC
Labels: bug, javascript
