### ISSUE TITLE
 InboxScannerService is not working as expected

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/opencast#1165] opened 2019-10-25 09:31 UTC
**Describe the bug**
Coping zip files to inbox folder doesn't start a workflow.  After change and save org.opencastproject.ingest.scanner.InboxScannerService-inbox.cfg file then the scanner starts track the folder and creates a workflow. If another zip copied after a while nothing will happens

**To Reproduce**
1. Create a media zip file and copy it to inbox folder as described here https://docs.opencast.org/r/7.x/admin/#configuration/inbox/#step-1-configure-an-inboxscannerservice
2. Nothing happened . Edit and save org.opencastproject.ingest.scanner.InboxScannerService-inbox.cfg file
3. A workflow is now created 
4. After X minutes create and copy another one.
5. A new workflow should be created (but nothing happens)

**Environment Information**
 - OS: Ubuntu 18.04
 - Browser Chrome/FF
 - Opencast 7.3

**Comment by stefanosgeo** [comment] 2020-01-20 07:48
I am not sure if this helps but after 2 restarts (due to activemq connection problems) this seems to work now...

**Comment by lkiesow** [comment] 2020-05-03 18:58
Closing this since it seems to work now and no one else could reproduce this.

**Closed as completed by lkiesow** 2020-05-03 18:58 UTC
