### ISSUE TITLE
Stand-alone editor is stuck in animation "Generating Waveform" for videos without audio track

### ISSUE THREAD

**Issue by geichelberger** [opencast/opencast#2491] opened 2021-04-13 17:26 UTC
Uploading a video without an audio track causes an exception in the stand-alone editor ui which leads to the "Generating Waveform" animation not being stopped.

Browser-Console Error: 
`DOMException: The buffer passed to decodeAudioData contains an unknown content type.  waveform.js:46:26`

1. Upload video without audio track.
2. Open the stand-alone editor
3. "Generating Waveform" animation never stops

**Environment Information**
 - OS: Fedora 33
 - Browser Firefox,Chrome
 - Opencast 10-SNAPSHOT

**Comment by lkiesow** [comment] 2021-04-15 15:16
This seems like a duplicate of https://github.com/elan-ev/opencast-editor/issues/254 and this might already be fixed with https://github.com/elan-ev/opencast-editor/pull/236

**Comment by lkiesow** [comment] 2021-05-02 17:55
Fixed in https://github.com/elan-ev/opencast-editor/pull/236
Will be resolved with the next editor update

**Closed as completed** 2021-06-10 08:34 UTC
Labels: bug, elan e.V., editor
